#!/usr/bin/perl -w
$x = {
   "transferStatus" => [
      "undefined",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "Failed",
      "undefined",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "undefined",
      "Failed",
      "undefined",
      "Failed",
      "Failed",
      "Failed",
      "undefined",
      "undefined",
      "Failed",
      "Failed",
      "Failed",
      "Failed",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "Failed",
      "Failed",
      "Failed",
      "undefined",
      "undefined",
      "undefined",
      "undefined",
      "Failed",
      "undefined",
      "undefined",
      "undefined",
      "Failed",
      "Failed",
      "undefined",
      "Failed",
      "undefined",
      "undefined",
      "Failed",
      "undefined",
      "Failed",
      "Failed",
      "Failed",
      "undefined"
   ],
   "LFNs" => [
      "/store/temp/user/dciangot/my_cool_dataset/file-1984-779.root",
      undef,
      undef,
      undef,
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1838-679.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1382-118.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1582-513.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1095-122.root",
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1468-967.root",
      undef,
      undef,
      undef,
      undef,
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1722-523.root",
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1528-387.root",
      undef,
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1608-227.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1610-527.root",
      undef,
      undef,
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1440-623.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1162-641.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1561-374.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1500-5.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1671-764.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1432-285.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1920-551.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1446-31.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1337-710.root",
      undef,
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1306-461.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1850-860.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1626-192.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1618-133.root",
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1844-418.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1536-843.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1400-946.root",
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1652-521.root",
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1440-48.root",
      "/store/temp/user/dciangot/my_cool_dataset/file-1859-562.root",
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1953-16.root",
      undef,
      undef,
      undef,
      "/store/temp/user/dciangot/my_cool_dataset/file-1074-63.root"
   ],
   "failure_reason" => [
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'",
      "Job ended in state 'Failed'"
   ],
   "timestamp" => [
      undef,
      1394200427,
      1394200427,
      1394200427,
      1394200427,
      1394200427,
      undef,
      undef,
      undef,
      undef,
      1394200427,
      undef,
      1394200427,
      1394200427,
      1394200427,
      1394200427,
      1394200427,
      1394200427,
      undef,
      1394200427,
      undef,
      1394200427,
      1394200427,
      1394200427,
      undef,
      undef,
      1394200427,
      1394200427,
      1394200427,
      1394200427,
      undef,
      undef,
      undef,
      undef,
      undef,
      undef,
      undef,
      undef,
      undef,
      1394200427,
      1394200427,
      1394200427,
      undef,
      undef,
      undef,
      undef,
      1394200427,
      undef,
      undef,
      undef,
      1394200427,
      1394200427,
      undef,
      1394200427,
      undef,
      undef,
      1394200427,
      undef,
      1394200427,
      1394200427,
      1394200427,
      undef
   ],
   "USERNAME" => "dciangot"
};
$DB::single=1;
print "All done\n";
